"""creating

Revision ID: ab3136ec51ee
Revises: 
Create Date: 2020-05-19 12:13:48.924796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3136ec51ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemid', sa.String(length=64), nullable=True),
    sa.Column('itemname', sa.String(length=64), nullable=True),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('ph', sa.String(length=64), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('pin', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buy_email'), 'buy', ['email'], unique=False)
    op.create_index(op.f('ix_buy_location'), 'buy', ['location'], unique=False)
    op.create_index(op.f('ix_buy_name'), 'buy', ['name'], unique=False)
    op.create_table('items',
    sa.Column('itemid', sa.String(length=64), nullable=False),
    sa.Column('itemname', sa.String(length=64), nullable=True),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('itemid')
    )
    op.create_index(op.f('ix_items_itemname'), 'items', ['itemname'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('ph', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_items_itemname'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_buy_name'), table_name='buy')
    op.drop_index(op.f('ix_buy_location'), table_name='buy')
    op.drop_index(op.f('ix_buy_email'), table_name='buy')
    op.drop_table('buy')
    # ### end Alembic commands ###
